# Generated by Django 2.1.5 on 2019-01-24 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangobin', '0006_auto_20190124_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='defaulr_expiration',
            new_name='default_expiration',
        ),
    ]
